"""Build data/manifest.json and data/gaps_report.md from the recorded parquet."""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from kalshi_research.writer import build_manifest  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"

# expected sampling interval per source, seconds (from the recorder config)
EXPECTED = {
    "kalshi_trades": 1.0,
    "kalshi_book_tier1": 0.25,
    "kalshi_book_tier2": 0.5,
    "kalshi_status": 30.0,
    "ext_spot": 2.0,
    "ext_perp": 10.0,
    "ext_deribit": 30.0,
    "ext_deribit_chain": 300.0,
    "ext_nws": 300.0,
}


def main() -> None:
    man = build_manifest(RAW, ROOT / "data" / "manifest.json")
    print(f"manifest: {man['n_files']} files, {man['total_rows']} rows")

    lines = [
        "# Recorded data: coverage and gaps",
        "",
        "Generated by `scripts/build_manifest_and_gaps.py`. A gap is only a defect "
        "if `trading_active` was true throughout it -- Kalshi halts trading daily "
        "(observed 07:00-09:00 UTC on 2026-07-30), and those windows are recorded in "
        "`source=kalshi_status` precisely so they can be distinguished from recorder "
        "failures.",
        "",
    ]

    # trading-halt windows, for attribution
    halt_note = "no status rows recorded"
    sp = RAW / "source=kalshi_status"
    if sp.exists():
        fs = sorted(sp.rglob("*.parquet"))
        if fs:
            st = pd.concat([pd.read_parquet(f) for f in fs], ignore_index=True)
            st = st.sort_values("recv_ns")
            frac = float(st.trading_active.mean())
            halt_note = (
                f"{len(st)} status samples; `trading_active` true in "
                f"{100*frac:.1f}% of them"
            )
    lines += [f"**Exchange status during recording:** {halt_note}", ""]

    lines += ["| source | files | rows | first (UTC) | last (UTC) | span | "
              "median gap (s) | max gap (s) | gaps > 10x expected |",
              "|---|---|---|---|---|---|---|---|---|"]

    for src_dir in sorted(RAW.glob("source=*")):
        src = src_dir.name.split("=", 1)[1]
        fs = sorted(src_dir.rglob("*.parquet"))
        if not fs:
            continue
        df = pd.concat([pd.read_parquet(f) for f in fs], ignore_index=True)
        col = next((c for c in ("recv_ns", "event_ns", "write_ns") if c in df.columns), None)
        if col is None or df.empty:
            lines.append(f"| {src} | {len(fs)} | {len(df)} | - | - | - | - | - | - |")
            continue
        ts = pd.to_numeric(df[col], errors="coerce").dropna().sort_values()
        # collapse rows sharing a poll timestamp (a book snapshot is many rows)
        uniq = pd.Series(ts.unique())
        d = uniq.diff().dropna() / 1e9
        exp = EXPECTED.get(src, 60.0)
        n_big = int((d > 10 * exp).sum())
        first = pd.Timestamp(int(uniq.iloc[0]), unit="ns", tz="UTC")
        last = pd.Timestamp(int(uniq.iloc[-1]), unit="ns", tz="UTC")
        lines.append(
            f"| {src} | {len(fs)} | {len(df)} | {first:%Y-%m-%d %H:%M:%S} | "
            f"{last:%Y-%m-%d %H:%M:%S} | {(last-first)} | "
            f"{d.median() if len(d) else float('nan'):.2f} | "
            f"{d.max() if len(d) else float('nan'):.1f} | {n_big} |"
        )

    lines += [
        "",
        "## Known limitations of this dataset",
        "",
        "1. **Book rows carry no exchange event timestamp.** Kalshi's WebSocket needs a "
        "signed key even for public channels, so recorders poll REST. Every book row has "
        "`recv_ns` and `write_ns` but `event_ns` is null by necessity -- REST snapshots do "
        "not expose the exchange-side timestamp. Any latency analysis is therefore "
        "round-trip, not one-way.",
        "2. **Books are snapshots, not deltas.** Between two polls of the same market the "
        "book may have moved and returned; we cannot see it. Tier1 rotates 24 markets at "
        "4 req/s (~6 s per market), tier2 140 markets at 2 req/s (~70 s per market).",
        "3. **Recording began 2026-07-30 ~07:30 UTC**, inside the daily trading halt, so "
        "the first ~90 minutes contain no trades by construction.",
        "4. **Perp data is OKX and Deribit, not Binance** -- Binance returns HTTP 451 and "
        "Bybit HTTP 403 from this host.",
    ]

    (ROOT / "data" / "gaps_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {ROOT/'data'/'gaps_report.md'}")
    print("\n".join(lines[6:20]))


if __name__ == "__main__":
    main()
