"""add robust copyable roi

Revision ID: 255065d32ee4
Revises: e44e642f8c2f
Create Date: 2026-07-29 23:58:59.679352
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# The models use custom column types (UtcDateTime, SqliteSafeNumeric); autogenerate
# renders them as ``app.db.<Type>()``, so this import must always be present.
import app.db


revision: str = '255065d32ee4'
down_revision: str | None = 'e44e642f8c2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copyable_roi_median', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('copyable_roi_trimmed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('copyable_outlier_dependence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_metrics', schema=None) as batch_op:
        batch_op.drop_column('copyable_outlier_dependence')
        batch_op.drop_column('copyable_roi_trimmed')
        batch_op.drop_column('copyable_roi_median')

    # ### end Alembic commands ###
