"""initial schema

Revision ID: d0f0cef66b0a
Revises: 
Create Date: 2026-07-29 20:22:43.829971
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# The models use custom column types (UtcDateTime, SqliteSafeNumeric); autogenerate
# renders them as ``app.db.<Type>()``, so this import must always be present.
import app.db


revision: str = 'd0f0cef66b0a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_settings_key'), ['key'], unique=True)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('slippage_bps', sa.Integer(), nullable=False),
    sa.Column('fee_bps', sa.Integer(), nullable=False),
    sa.Column('exit_strategy', sa.String(length=30), nullable=False),
    sa.Column('stake_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('consensus_required', sa.Integer(), nullable=False),
    sa.Column('period_start', app.db.UtcDateTime(), nullable=False),
    sa.Column('period_end', app.db.UtcDateTime(), nullable=False),
    sa.Column('train_end', app.db.UtcDateTime(), nullable=True),
    sa.Column('validation_end', app.db.UtcDateTime(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('total_staked', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('total_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('avg_trade_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('median_trade_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('sharpe_like', sa.Float(), nullable=True),
    sa.Column('in_sample_return', sa.Float(), nullable=True),
    sa.Column('out_of_sample_return', sa.Float(), nullable=True),
    sa.Column('validation_return', sa.Float(), nullable=True),
    sa.Column('walk_forward_json', sa.Text(), nullable=True),
    sa.Column('equity_curve_json', sa.Text(), nullable=True),
    sa.Column('drawdown_curve_json', sa.Text(), nullable=True),
    sa.Column('delay_sensitivity_json', sa.Text(), nullable=True),
    sa.Column('parameter_sensitivity_json', sa.Text(), nullable=True),
    sa.Column('outcome_distribution_json', sa.Text(), nullable=True),
    sa.Column('by_market_type_json', sa.Text(), nullable=True),
    sa.Column('by_wallet_json', sa.Text(), nullable=True),
    sa.Column('return_ci_low', sa.Float(), nullable=True),
    sa.Column('return_ci_high', sa.Float(), nullable=True),
    sa.Column('pct_pnl_from_top_trade', sa.Float(), nullable=True),
    sa.Column('lookahead_violations', sa.Integer(), nullable=False),
    sa.Column('data_quality_warnings', sa.Text(), nullable=True),
    sa.Column('skipped_trades', sa.Integer(), nullable=False),
    sa.Column('skip_reasons_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_backtest_status_created', ['status', 'created_at'], unique=False)

    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('wallets_tracked', sa.Integer(), nullable=False),
    sa.Column('wallets_stale', sa.Integer(), nullable=False),
    sa.Column('markets_tracked', sa.Integer(), nullable=False),
    sa.Column('markets_needing_review', sa.Integer(), nullable=False),
    sa.Column('transactions_total', sa.Integer(), nullable=False),
    sa.Column('transactions_unmatched_market', sa.Integer(), nullable=False),
    sa.Column('positions_total', sa.Integer(), nullable=False),
    sa.Column('positions_low_confidence', sa.Integer(), nullable=False),
    sa.Column('price_quality_breakdown_json', sa.Text(), nullable=True),
    sa.Column('avg_data_confidence', sa.Float(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_reports_generated_at'), ['generated_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamma_event_id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('ticker', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('start_date', app.db.UtcDateTime(), nullable=True),
    sa.Column('end_date', app.db.UtcDateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('liquidity', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('volume', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('volume_24hr', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('sport_category', sa.String(length=20), nullable=False),
    sa.Column('tournament', sa.String(length=200), nullable=True),
    sa.Column('player_a', sa.String(length=120), nullable=True),
    sa.Column('player_b', sa.String(length=120), nullable=True),
    sa.Column('best_of', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('tour', sa.String(length=20), nullable=True),
    sa.Column('synced_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_gamma_event_id'), ['gamma_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_player_a'), ['player_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_player_b'), ['player_b'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_sport_category'), ['sport_category'], unique=False)
        batch_op.create_index('ix_events_sport_closed', ['sport_category', 'closed'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tournament'), ['tournament'], unique=False)

    op.create_table('manual_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_key', sa.String(length=120), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_key', 'field', name='uq_override_target')
    )
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_overrides_entity_key'), ['entity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_overrides_entity_type'), ['entity_type'], unique=False)

    op.create_table('paper_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('trades_entered', sa.Integer(), nullable=False),
    sa.Column('trades_closed', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('stake_deployed', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('entries_blocked_by_risk', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', name='uq_paper_daily_date')
    )
    with op.batch_alter_table('paper_daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_daily_stats_stat_date'), ['stat_date'], unique=False)

    op.create_table('schema_drift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('missing_fields', sa.Text(), nullable=True),
    sa.Column('new_fields', sa.Text(), nullable=True),
    sa.Column('sample_payload', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('detected_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'missing_fields', 'new_fields', name='uq_drift')
    )
    with op.batch_alter_table('schema_drift_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schema_drift_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schema_drift_events_endpoint'), ['endpoint'], unique=False)

    op.create_table('system_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=15), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('component', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('job_uid', sa.String(length=40), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_system_error_fingerprint')
    )
    with op.batch_alter_table('system_errors', schema=None) as batch_op:
        batch_op.create_index('ix_errors_recent', ['resolved', 'last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_errors_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_errors_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_errors_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_errors_severity'), ['severity'], unique=False)

    op.create_table('wallet_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('gamma_market_id', sa.String(length=40), nullable=True),
    sa.Column('question_id', sa.String(length=80), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('sport_category', sa.String(length=20), nullable=False),
    sa.Column('is_tennis', sa.Boolean(), nullable=False),
    sa.Column('tennis_market_type', sa.String(length=30), nullable=False),
    sa.Column('sports_market_type_raw', sa.String(length=60), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('classification_methods', sa.Text(), nullable=True),
    sa.Column('classification_notes', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_human', sa.Boolean(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=True),
    sa.Column('handicap_line', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('total_line', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('game_start_time', app.db.UtcDateTime(), nullable=True),
    sa.Column('start_date', app.db.UtcDateTime(), nullable=True),
    sa.Column('end_date', app.db.UtcDateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('accepting_orders', sa.Boolean(), nullable=False),
    sa.Column('enable_order_book', sa.Boolean(), nullable=False),
    sa.Column('neg_risk', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('winning_outcome_index', sa.Integer(), nullable=True),
    sa.Column('resolved_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('uma_resolution_statuses', sa.String(length=120), nullable=True),
    sa.Column('liquidity', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('volume', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('volume_24hr', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('spread', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('best_bid', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('best_ask', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('last_trade_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('tick_size', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('min_order_size', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('maker_fee_bps', sa.Integer(), nullable=True),
    sa.Column('taker_fee_bps', sa.Integer(), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('synced_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_closed'), ['closed'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_condition_id'), ['condition_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_markets_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_game_start_time'), ['game_start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_gamma_market_id'), ['gamma_market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_is_tennis'), ['is_tennis'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_sport_category'), ['sport_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_tennis_market_type'), ['tennis_market_type'], unique=False)
        batch_op.create_index('ix_markets_tennis_open', ['is_tennis', 'closed', 'game_start_time'], unique=False)
        batch_op.create_index('ix_markets_tennis_type', ['is_tennis', 'tennis_market_type'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('pseudonym', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manually_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('on_watchlist', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('suspected_cluster_id', sa.Integer(), nullable=True),
    sa.Column('first_activity_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('last_activity_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('last_synced_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('last_sync_success_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('sync_cursor_ts', sa.Integer(), nullable=True),
    sa.Column('backfill_complete', sa.Boolean(), nullable=False),
    sa.Column('observed_portfolio_value', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('sync_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['suspected_cluster_id'], ['wallet_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallets_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index('ix_wallets_status_approved', ['status', 'manually_approved'], unique=False)
        batch_op.create_index('ix_wallets_sync', ['status', 'sync_priority', 'last_sync_success_at'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=60), nullable=False),
    sa.Column('job_uid', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_skipped_duplicate', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('http_requests', sa.Integer(), nullable=False),
    sa.Column('http_retries', sa.Integer(), nullable=False),
    sa.Column('rate_limit_events', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_uid')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_index('ix_jobs_type_started', ['job_type', 'started_at'], unique=False)

    op.create_table('liquidity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('observed_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('best_bid', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('best_ask', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('midpoint', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('spread', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('bid_depth_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('ask_depth_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('ask_depth_1c_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('ask_depth_5c_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('tick_size', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('bids_json', sa.Text(), nullable=True),
    sa.Column('asks_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'timestamp', name='uq_liquidity_token_ts')
    )
    with op.batch_alter_table('liquidity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidity_snapshots_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidity_snapshots_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidity_snapshots_token_id'), ['token_id'], unique=False)
        batch_op.create_index('ix_liquidity_token_ts', ['token_id', 'timestamp'], unique=False)

    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('observed_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=False),
    sa.Column('size', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('side', sa.String(length=6), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_prices_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_token_id'), ['token_id'], unique=False)
        batch_op.create_index('ix_price_token_kind_ts', ['token_id', 'kind', 'timestamp'], unique=False)
        batch_op.create_index('ix_price_token_ts', ['token_id', 'timestamp'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('outcome_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('last_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'outcome_index', name='uq_outcome_market_index')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_token_id'), ['token_id'], unique=True)

    op.create_table('wallet_cluster_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('shared_market_count', sa.Integer(), nullable=False),
    sa.Column('jaccard_similarity', sa.Float(), nullable=False),
    sa.Column('timing_correlation', sa.Float(), nullable=False),
    sa.Column('size_correlation', sa.Float(), nullable=False),
    sa.Column('coordinated_exit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['wallet_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'wallet_id', name='uq_cluster_member')
    )
    with op.batch_alter_table('wallet_cluster_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_cluster_members_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_cluster_members_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('wallet_metric_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('completed_positions', sa.Integer(), nullable=False),
    sa.Column('net_profit', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('copyable_roi', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'scope', 'snapshot_date', name='uq_metric_history_day')
    )
    with op.batch_alter_table('wallet_metric_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_metric_history_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_metric_history_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('wallet_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_positions', sa.Integer(), nullable=False),
    sa.Column('completed_positions', sa.Integer(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('volume_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('capital_deployed', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('gross_profit', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('gross_loss', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('net_profit', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('fees_paid', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('return_on_capital', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_profit_per_trade', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('median_profit_per_trade', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('expected_value_per_dollar', sa.Float(), nullable=True),
    sa.Column('avg_entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('avg_holding_seconds', sa.Integer(), nullable=True),
    sa.Column('median_holding_seconds', sa.Integer(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('max_drawdown_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('longest_win_streak', sa.Integer(), nullable=False),
    sa.Column('longest_loss_streak', sa.Integer(), nullable=False),
    sa.Column('pct_profit_from_largest_trade', sa.Float(), nullable=True),
    sa.Column('pct_profit_from_top5_trades', sa.Float(), nullable=True),
    sa.Column('pnl_std_dev', sa.Float(), nullable=True),
    sa.Column('sharpe_like', sa.Float(), nullable=True),
    sa.Column('benchmark_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('copyable_roi', sa.Float(), nullable=True),
    sa.Column('copyable_win_rate', sa.Float(), nullable=True),
    sa.Column('copyable_net_profit', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('copyable_profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_copyability_score', sa.Float(), nullable=True),
    sa.Column('copyable_coverage', sa.Float(), nullable=True),
    sa.Column('avg_price_deterioration', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('roi_by_delay', sa.Text(), nullable=True),
    sa.Column('roi_ci_low', sa.Float(), nullable=True),
    sa.Column('roi_ci_high', sa.Float(), nullable=True),
    sa.Column('copyable_roi_ci_low', sa.Float(), nullable=True),
    sa.Column('copyable_roi_ci_high', sa.Float(), nullable=True),
    sa.Column('shrunk_copyable_roi', sa.Float(), nullable=True),
    sa.Column('prob_positive_edge', sa.Float(), nullable=True),
    sa.Column('sample_confidence', sa.Float(), nullable=True),
    sa.Column('performance_by_market_type', sa.Text(), nullable=True),
    sa.Column('performance_by_tournament', sa.Text(), nullable=True),
    sa.Column('performance_by_player', sa.Text(), nullable=True),
    sa.Column('performance_by_entry_bucket', sa.Text(), nullable=True),
    sa.Column('performance_by_size_bucket', sa.Text(), nullable=True),
    sa.Column('performance_by_period', sa.Text(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('computed_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'scope', name='uq_wallet_metrics_scope')
    )
    with op.batch_alter_table('wallet_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_metrics_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_wallet_metrics_scope_roi', ['scope', 'copyable_roi'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_metrics_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('wallet_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('copyable_roi_score', sa.Float(), nullable=False),
    sa.Column('profit_factor_score', sa.Float(), nullable=False),
    sa.Column('sample_confidence_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('drawdown_score', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('liquidity_fit_score', sa.Float(), nullable=False),
    sa.Column('concentration_score', sa.Float(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('penalties_applied', sa.Text(), nullable=True),
    sa.Column('total_penalty_multiplier', sa.Float(), nullable=False),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('disqualification_reasons', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'scope', name='uq_wallet_score_scope')
    )
    with op.batch_alter_table('wallet_scores', schema=None) as batch_op:
        batch_op.create_index('ix_wallet_score_rank', ['scope', 'qualified', 'skill_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_scores_qualified'), ['qualified'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_scores_skill_score'), ['skill_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_scores_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('wallet_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'tag', name='uq_wallet_tag')
    )
    with op.batch_alter_table('wallet_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_tags_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('raw_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('transaction_hash', sa.String(length=80), nullable=True),
    sa.Column('activity_timestamp', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('ingested_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'dedupe_key', name='uq_raw_activity_dedupe')
    )
    with op.batch_alter_table('raw_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_activity_activity_timestamp'), ['activity_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_activity_transaction_hash'), ['transaction_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_activity_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_index('ix_raw_activity_wallet_ts', ['wallet_id', 'activity_timestamp'], unique=False)

    op.create_table('reconstructed_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('outcome_index', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accounting_method', sa.String(length=20), nullable=False),
    sa.Column('opened_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('opened_ts', sa.Integer(), nullable=False),
    sa.Column('first_entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=False),
    sa.Column('avg_entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=False),
    sa.Column('entry_tx_count', sa.Integer(), nullable=False),
    sa.Column('accumulated', sa.Boolean(), nullable=False),
    sa.Column('scaled_in_at_worse_prices', sa.Boolean(), nullable=False),
    sa.Column('closed_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('closed_ts', sa.Integer(), nullable=True),
    sa.Column('avg_exit_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('exit_tx_count', sa.Integer(), nullable=False),
    sa.Column('partial_exit_count', sa.Integer(), nullable=False),
    sa.Column('settled_by_redemption', sa.Boolean(), nullable=False),
    sa.Column('total_shares_bought', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('total_shares_sold', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('current_shares', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('max_shares', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('capital_committed', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('max_capital_at_risk', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('pct_of_wallet_capital', sa.Float(), nullable=True),
    sa.Column('realized_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('unrealized_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('gross_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('fees_paid', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('net_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('holding_seconds', sa.Integer(), nullable=True),
    sa.Column('entry_phase', sa.String(length=15), nullable=False),
    sa.Column('tennis_market_type', sa.String(length=30), nullable=False),
    sa.Column('is_tennis', sa.Boolean(), nullable=False),
    sa.Column('behaviour', sa.String(length=30), nullable=False),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('held_both_outcomes', sa.Boolean(), nullable=False),
    sa.Column('reconstruction_confidence', sa.Float(), nullable=False),
    sa.Column('reconstruction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'token_id', 'sequence', name='uq_position_seq')
    )
    with op.batch_alter_table('reconstructed_positions', schema=None) as batch_op:
        batch_op.create_index('ix_position_opened', ['is_tennis', 'opened_ts'], unique=False)
        batch_op.create_index('ix_position_tennis_closed', ['is_tennis', 'status', 'closed_ts'], unique=False)
        batch_op.create_index('ix_position_wallet_tennis', ['wallet_id', 'is_tennis', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_behaviour'), ['behaviour'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_entry_phase'), ['entry_phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_is_tennis'), ['is_tennis'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_opened_ts'), ['opened_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_outcome_id'), ['outcome_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_tennis_market_type'), ['tennis_market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_token_id'), ['token_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconstructed_positions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('outcome_label', sa.String(length=200), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('first_wallet_trade_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('last_wallet_trade_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('detected_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('evaluated_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('expires_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('signal_age_seconds', sa.Integer(), nullable=True),
    sa.Column('market_phase', sa.String(length=15), nullable=False),
    sa.Column('wallet_entry_price_min', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('wallet_entry_price_max', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('wallet_entry_price_median', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('current_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('estimated_follower_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('price_deterioration', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('available_liquidity', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('spread', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('total_wallet_position_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('wallet_count', sa.Integer(), nullable=False),
    sa.Column('independent_cluster_count', sa.Integer(), nullable=False),
    sa.Column('median_skill_score', sa.Float(), nullable=True),
    sa.Column('median_copyable_roi', sa.Float(), nullable=True),
    sa.Column('copyability_score', sa.Float(), nullable=True),
    sa.Column('consensus_score', sa.Float(), nullable=True),
    sa.Column('estimated_edge', sa.Float(), nullable=True),
    sa.Column('edge_method', sa.String(length=40), nullable=True),
    sa.Column('data_confidence', sa.Float(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('rejection_reasons', sa.Text(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('qualification_detail', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index('ix_signals_feed', ['status', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_first_wallet_trade_at'), ['first_wallet_trade_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_qualified'), ['qualified'], unique=False)
        batch_op.create_index('ix_signals_qualified_time', ['qualified', 'detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_token_id'), ['token_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('read_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'channel', 'alert_type', name='uq_alert_channel')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index('ix_alerts_created', ['created_at', 'delivered'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_signal_id'), ['signal_id'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('decision_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('entered_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('exited_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('wallet_entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('fill_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('exit_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('stake_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('exit_reason', sa.String(length=60), nullable=True),
    sa.Column('market_type', sa.String(length=30), nullable=True),
    sa.Column('market_phase', sa.String(length=15), nullable=True),
    sa.Column('copyability_score', sa.Float(), nullable=True),
    sa.Column('price_source_quality', sa.String(length=25), nullable=True),
    sa.Column('split', sa.String(length=12), nullable=True),
    sa.Column('decision_inputs_json', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['reconstructed_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_trade_run_time', ['run_id', 'decision_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_trades_decision_at'), ['decision_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_trades_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_trades_split'), ['split'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_trades_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('normalized_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('raw_activity_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('token_id', sa.String(length=90), nullable=True),
    sa.Column('outcome_index', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=6), nullable=True),
    sa.Column('size', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('usdc_size', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('fee_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('occurred_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=80), nullable=True),
    sa.Column('market_phase', sa.String(length=15), nullable=False),
    sa.Column('seconds_to_start', sa.Integer(), nullable=True),
    sa.Column('is_tennis', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_activity_id'], ['raw_activity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'transaction_hash', 'token_id', 'side', 'size', 'price', name='uq_normalized_tx')
    )
    with op.batch_alter_table('normalized_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_norm_tx_tennis_time', ['is_tennis', 'timestamp'], unique=False)
        batch_op.create_index('ix_norm_tx_token_time', ['token_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_norm_tx_unprocessed', ['wallet_id', 'processed', 'timestamp'], unique=False)
        batch_op.create_index('ix_norm_tx_wallet_time', ['wallet_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_condition_id'), ['condition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_is_tennis'), ['is_tennis'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_outcome_id'), ['outcome_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_token_id'), ['token_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_transaction_hash'), ['transaction_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_transactions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.String(length=90), nullable=False),
    sa.Column('outcome_label', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_strategy', sa.String(length=30), nullable=False),
    sa.Column('signal_detected_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('execution_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('entered_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('wallet_entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('reference_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('fill_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('slippage_applied', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('fees_applied', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('stake_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('shares', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('stake_reduced_for_liquidity', sa.Boolean(), nullable=False),
    sa.Column('exited_at', app.db.UtcDateTime(), nullable=True),
    sa.Column('exit_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('exit_reason', sa.String(length=60), nullable=True),
    sa.Column('settled_by_resolution', sa.Boolean(), nullable=False),
    sa.Column('realized_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('unrealized_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('holding_seconds', sa.Integer(), nullable=True),
    sa.Column('wallet_roi', sa.Float(), nullable=True),
    sa.Column('roi_gap_vs_wallet', sa.Float(), nullable=True),
    sa.Column('price_source_quality', sa.String(length=25), nullable=True),
    sa.Column('data_confidence', sa.Float(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_backtest', sa.Boolean(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index('ix_paper_live', ['is_backtest', 'status'], unique=False)
        batch_op.create_index('ix_paper_status_entered', ['status', 'entered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_backtest_run_id'), ['backtest_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_entered_at'), ['entered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_is_backtest'), ['is_backtest'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_token_id'), ['token_id'], unique=False)

    op.create_table('signal_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('position_usdc', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('traded_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('copyable_roi', sa.Float(), nullable=True),
    sa.Column('tennis_trade_count', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('counted_as_independent', sa.Boolean(), nullable=False),
    sa.Column('is_position_increase', sa.Boolean(), nullable=False),
    sa.Column('has_begun_exiting', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['reconstructed_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'wallet_id', name='uq_signal_wallet')
    )
    with op.batch_alter_table('signal_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_wallets_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_wallets_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('trade_copyability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('wallet_entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=False),
    sa.Column('price_before', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('price_after_delay', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('estimated_fill_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('price_deterioration', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('price_deterioration_pct', sa.Float(), nullable=True),
    sa.Column('slippage', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('spread_at_entry', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('available_liquidity', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('follower_exit_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('follower_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('follower_roi', sa.Float(), nullable=True),
    sa.Column('follower_is_win', sa.Boolean(), nullable=True),
    sa.Column('copyability_score', sa.Float(), nullable=False),
    sa.Column('copyability_components', sa.Text(), nullable=True),
    sa.Column('price_source_quality', sa.String(length=25), nullable=False),
    sa.Column('data_confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('computed_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['reconstructed_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'delay_seconds', name='uq_copyability_delay')
    )
    with op.batch_alter_table('trade_copyability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_copyability_delay_seconds'), ['delay_seconds'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_copyability_position_id'), ['position_id'], unique=False)

    op.create_table('paper_trade_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_trade_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=25), nullable=False),
    sa.Column('occurred_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=True),
    sa.Column('shares', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_trade_id'], ['paper_trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trade_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trade_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trade_events_paper_trade_id'), ['paper_trade_id'], unique=False)

    op.create_table('position_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('lot_index', sa.Integer(), nullable=False),
    sa.Column('acquired_ts', sa.Integer(), nullable=False),
    sa.Column('acquired_at', app.db.UtcDateTime(), nullable=False),
    sa.Column('shares', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('shares_remaining', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('entry_price', app.db.SqliteSafeNumeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_basis', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('realized_pnl', app.db.SqliteSafeNumeric(precision=28, scale=6), nullable=False),
    sa.Column('fully_consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UtcDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['reconstructed_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['normalized_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'lot_index', name='uq_lot_index')
    )
    with op.batch_alter_table('position_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_lots_position_id'), ['position_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_lots_position_id'))

    op.drop_table('position_lots')
    with op.batch_alter_table('paper_trade_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trade_events_paper_trade_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trade_events_event_type'))

    op.drop_table('paper_trade_events')
    with op.batch_alter_table('trade_copyability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_copyability_position_id'))
        batch_op.drop_index(batch_op.f('ix_trade_copyability_delay_seconds'))

    op.drop_table('trade_copyability')
    with op.batch_alter_table('signal_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_wallets_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_signal_wallets_signal_id'))

    op.drop_table('signal_wallets')
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trades_token_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_status'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_signal_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_market_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_is_backtest'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_entered_at'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_backtest_run_id'))
        batch_op.drop_index('ix_paper_status_entered')
        batch_op.drop_index('ix_paper_live')

    op.drop_table('paper_trades')
    with op.batch_alter_table('normalized_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_transaction_hash'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_token_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_processed'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_outcome_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_market_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_is_tennis'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_condition_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_transactions_activity_type'))
        batch_op.drop_index('ix_norm_tx_wallet_time')
        batch_op.drop_index('ix_norm_tx_unprocessed')
        batch_op.drop_index('ix_norm_tx_token_time')
        batch_op.drop_index('ix_norm_tx_tennis_time')

    op.drop_table('normalized_transactions')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_trades_split'))
        batch_op.drop_index(batch_op.f('ix_backtest_trades_run_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_trades_decision_at'))
        batch_op.drop_index('ix_backtest_trade_run_time')

    op.drop_table('backtest_trades')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_signal_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index('ix_alerts_created')
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_token_id'))
        batch_op.drop_index(batch_op.f('ix_signals_status'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index('ix_signals_qualified_time')
        batch_op.drop_index(batch_op.f('ix_signals_qualified'))
        batch_op.drop_index(batch_op.f('ix_signals_market_id'))
        batch_op.drop_index(batch_op.f('ix_signals_first_wallet_trade_at'))
        batch_op.drop_index('ix_signals_feed')
        batch_op.drop_index(batch_op.f('ix_signals_detected_at'))
        batch_op.drop_index(batch_op.f('ix_signals_condition_id'))

    op.drop_table('signals')
    with op.batch_alter_table('reconstructed_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_token_id'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_tennis_market_type'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_status'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_outcome_id'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_opened_ts'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_opened_at'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_market_id'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_is_tennis'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_entry_phase'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_condition_id'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_closed_at'))
        batch_op.drop_index(batch_op.f('ix_reconstructed_positions_behaviour'))
        batch_op.drop_index('ix_position_wallet_tennis')
        batch_op.drop_index('ix_position_tennis_closed')
        batch_op.drop_index('ix_position_opened')

    op.drop_table('reconstructed_positions')
    with op.batch_alter_table('raw_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_activity_wallet_ts')
        batch_op.drop_index(batch_op.f('ix_raw_activity_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_raw_activity_transaction_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_activity_activity_timestamp'))

    op.drop_table('raw_activity')
    with op.batch_alter_table('wallet_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_tags_wallet_id'))

    op.drop_table('wallet_tags')
    with op.batch_alter_table('wallet_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_scores_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_scores_skill_score'))
        batch_op.drop_index(batch_op.f('ix_wallet_scores_qualified'))
        batch_op.drop_index('ix_wallet_score_rank')

    op.drop_table('wallet_scores')
    with op.batch_alter_table('wallet_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_metrics_wallet_id'))
        batch_op.drop_index('ix_wallet_metrics_scope_roi')
        batch_op.drop_index(batch_op.f('ix_wallet_metrics_scope'))

    op.drop_table('wallet_metrics')
    with op.batch_alter_table('wallet_metric_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_metric_history_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_metric_history_snapshot_date'))

    op.drop_table('wallet_metric_history')
    with op.batch_alter_table('wallet_cluster_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_cluster_members_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_cluster_members_cluster_id'))

    op.drop_table('wallet_cluster_members')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_token_id'))
        batch_op.drop_index(batch_op.f('ix_outcomes_player_name'))
        batch_op.drop_index(batch_op.f('ix_outcomes_market_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_price_token_ts')
        batch_op.drop_index('ix_price_token_kind_ts')
        batch_op.drop_index(batch_op.f('ix_market_prices_token_id'))
        batch_op.drop_index(batch_op.f('ix_market_prices_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_prices_market_id'))
        batch_op.drop_index(batch_op.f('ix_market_prices_kind'))

    op.drop_table('market_prices')
    with op.batch_alter_table('liquidity_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_liquidity_token_ts')
        batch_op.drop_index(batch_op.f('ix_liquidity_snapshots_token_id'))
        batch_op.drop_index(batch_op.f('ix_liquidity_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_liquidity_snapshots_market_id'))

    op.drop_table('liquidity_snapshots')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_type_started')
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_started_at'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_job_type'))

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index('ix_wallets_sync')
        batch_op.drop_index('ix_wallets_status_approved')
        batch_op.drop_index(batch_op.f('ix_wallets_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_wallets_address'))

    op.drop_table('wallets')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index('ix_markets_tennis_type')
        batch_op.drop_index('ix_markets_tennis_open')
        batch_op.drop_index(batch_op.f('ix_markets_tennis_market_type'))
        batch_op.drop_index(batch_op.f('ix_markets_sport_category'))
        batch_op.drop_index(batch_op.f('ix_markets_slug'))
        batch_op.drop_index(batch_op.f('ix_markets_resolved'))
        batch_op.drop_index(batch_op.f('ix_markets_needs_review'))
        batch_op.drop_index(batch_op.f('ix_markets_is_tennis'))
        batch_op.drop_index(batch_op.f('ix_markets_gamma_market_id'))
        batch_op.drop_index(batch_op.f('ix_markets_game_start_time'))
        batch_op.drop_index(batch_op.f('ix_markets_event_id'))
        batch_op.drop_index(batch_op.f('ix_markets_condition_id'))
        batch_op.drop_index(batch_op.f('ix_markets_closed'))

    op.drop_table('markets')
    op.drop_table('wallet_clusters')
    with op.batch_alter_table('system_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_errors_severity'))
        batch_op.drop_index(batch_op.f('ix_system_errors_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_system_errors_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_system_errors_category'))
        batch_op.drop_index('ix_errors_recent')

    op.drop_table('system_errors')
    with op.batch_alter_table('schema_drift_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schema_drift_events_endpoint'))
        batch_op.drop_index(batch_op.f('ix_schema_drift_events_detected_at'))

    op.drop_table('schema_drift_events')
    with op.batch_alter_table('paper_daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_daily_stats_stat_date'))

    op.drop_table('paper_daily_stats')
    with op.batch_alter_table('manual_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_overrides_entity_type'))
        batch_op.drop_index(batch_op.f('ix_manual_overrides_entity_key'))

    op.drop_table('manual_overrides')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tournament'))
        batch_op.drop_index('ix_events_sport_closed')
        batch_op.drop_index(batch_op.f('ix_events_sport_category'))
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_player_b'))
        batch_op.drop_index(batch_op.f('ix_events_player_a'))
        batch_op.drop_index(batch_op.f('ix_events_gamma_event_id'))

    op.drop_table('events')
    with op.batch_alter_table('data_quality_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_reports_generated_at'))

    op.drop_table('data_quality_reports')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_status_created')
        batch_op.drop_index(batch_op.f('ix_backtest_runs_status'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_settings_key'))

    op.drop_table('application_settings')
    # ### end Alembic commands ###
