"""add equal-weighted roi

Revision ID: e44e642f8c2f
Revises: d0f0cef66b0a
Create Date: 2026-07-29 23:50:19.542674
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# The models use custom column types (UtcDateTime, SqliteSafeNumeric); autogenerate
# renders them as ``app.db.<Type>()``, so this import must always be present.
import app.db


revision: str = 'e44e642f8c2f'
down_revision: str | None = 'd0f0cef66b0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roi_equal_weighted', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_metrics', schema=None) as batch_op:
        batch_op.drop_column('roi_equal_weighted')

    # ### end Alembic commands ###
